version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
      - translate_service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/faq_db
      - REDIS_HOST=redis
      - TRANSLATE_API_URL=http://translate_service:5001/translate
    volumes:
      - ./backend:/app
    restart: always

  translate_service:
    build: ./translate_service
    ports:
      - "8000:8000"
    volumes:
      - ./translate_service:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
